### ISSUE TITLE
Update Build instructions

### ISSUE THREAD

**Issue by riginding** [TyberiusPrime/stm32f103_k2k#2]
Hi! Great project! 

I wanted to try out the firmware, the building instructions mention a `config.rs`.
I saw that `config.rs` was removed in this commit https://github.com/TyberiusPrime/stm32f103_k2k/commit/99add79f853aba67ee72f22a7eccc521ed09fff9

Is there a new way to define pins and layout?

**Comment by TyberiusPrime** [comment]
Sorry, missed your issue :(.

The key-matrix configuration is in main.rs, line 546f.
Couldn't make the borrow checker happy otherwise :(.
